### PR TITLE
feat(Table): Add composable table elements

### PR DESCRIPTION
**Pull request by aDogCalledSpot**

### CODE REVIEW

**Review by ctron — DISMISSED** [review]
I am not a fan of the component name `ComposableTable`. The description is correct! It just feels a bit verbose. Maybe `composable::Table`? I don't really have a better idea and that's just the name. The PR is great!!

**Comment by aDogCalledSpot** [comment]
One solution would be not to `pub use composable::*` in `table/mod.rs` which would mean that users would have to do something like this:

```rust
use patternfly_yew::prelude::*;
use patternfly_yew::components::table::composable::{self, *};

html! {
    <composable::Table>
        <TableRow>
            <TableData />
        </TableRow>
    </composable::Table>
}
```
I like it because it's a very explicit opt in

**Comment by aDogCalledSpot** [comment]
Ah no it's problematic. Since the prelude does `pub use crate::components::table::*`. This  approach creates a `patternfly_yew::prelude::composable` which would conflict with `composable` modules in any other module where we try to do the same. `<composable_table::Table>`  looks dumb as well.

**Comment by ctron** [comment]
Let's ignore that problem for now :)

**Comment by aDogCalledSpot** [comment]
Is this sufficient for closing #69?

**Review by ctron — DISMISSED** [review]

**Pull request merged**
