### PR TITLE
Bump version to 0.5.1

### PR DESCRIPTION
**Pull request by aDogCalledSpot**

### CODE REVIEW

**Comment by ctron** [comment]
I think you also need comment out (and update) the patch section.

**Comment by aDogCalledSpot** [comment]
> I think you also need comment out (and update) the patch section.

Does it then need to be commented back after?

**Comment by ctron** [comment]
I commented it out after the 0.5.0 release … just to use a properly released version for a few days :) … but for this project I think it's ok to use a git patch with a rev

**Review by ctron — APPROVED** [review]
You still need that path entry I think

**Comment by ctron** [comment]
:facepalm: I misread this for being a PR for the -quickstart project

**Comment by aDogCalledSpot** [comment]
Can we `cargo publish` this?

**Comment by ctron** [comment]
Done!

**Pull request merged**
