### PR TITLE
Implement checkbox

### PR DESCRIPTION
**Pull request by aDogCalledSpot**

### CODE REVIEW

**Comment by ctron** [comment]
I appreciate the PR, but I think we already had that: https://github.com/patternfly-yew/patternfly-yew/blob/main/src/components/form/check.rs

**Comment by aDogCalledSpot** [comment]
Oh dear, I kept searching for "Checkbox" and was coming up empty :sweat_smile: 

I guess my implementation has a few more features so we can merge most of it without problems.

However there are some breaking changes:

- Checkboxes have the indeterminate state, so `bool` isn't sufficient
- Supply the `Event` as an argument to the `onchange` callback
- The id is mandatory so we can use `for={props.id}` on the label for accessibility (also how it is done in patternfly-react)

**Comment by ctron** [comment]
Yea, I guess it makes sense to amend the current component. I would appreciate it, if we could stick to function components, unless necessary.

**Comment by aDogCalledSpot** [comment]
> stick to function components, unless necessary

Agreed, it's necessary here unfortunately because the indeterminate state can't be set via HTML but instead needs to be set via the node ref when the component is mounted.

The `render` method of the structural component allows this.

A lot of boilerplate for three lines of code :/

**Comment by ctron** [comment]
Can't you use a combination of https://docs.rs/yew/latest/yew/functional/fn.use_node_ref.html and https://docs.rs/yew/latest/yew/functional/fn.use_effect.html …

`use_effect` to execute when mounted and `use_noderef` for the `NodeRef`.

**Comment by ctron** [comment]
Cool. Can get a mix of both the existing and the new one?

**Comment by aDogCalledSpot** [comment]
Here's the new version.

- I removed the `children` prop in favour of `label` + `body`
- The id is being handled as in the old version (not mandatory)

I'm also partial towards naming the component "Checkbox" instead of "Check" to have it more in line with the React version but I've kept it as "Check" for now since that's how it's already implemented.

**Review by ctron — DISMISSED** [review]

**Comment by ctron** [comment]
I think it's ok to rename it. Not sure if we can use a `pub type Check = Checkbox` in combination with `#[deprecated]`. But having a breaking change before the final release would be ok for me.

I would also rename the properties to `*Properties` (instead of `*Props`, I know it was there before, but do prefer it now).

In any case, I think it's good to be merged. So let me know when you're done and I will press the button.

**Comment by aDogCalledSpot** [comment]
> I think it's ok to rename it. Not sure if we can use a pub type Check = Checkbox in combination with `#[deprecated]`. But having a breaking change before the final release would be ok for me.

Works :smiley: 

> I would also rename the properties `*Properties`

Done.

I also renamed the file to reflect the name of the component.

**Comment by aDogCalledSpot** [comment]
I would say it's ready.

**Review by ctron — APPROVED** [review]

**Comment by ctron** [comment]
@aDogCalledSpot I hope you don't mind … but I did revert adding the `Event` parameter to the callback. It let to a number of quite verbose changes. I am open to adding it, maybe we can find a better way.

**Comment by aDogCalledSpot** [comment]
I don't mind too much since it isn't something I need at the moment. I just thought it would be potentially be useful to a user and it wasn't difficult to implement. Tracking it in the separate issue seems like the right call for now 👍

**Pull request merged**
