### PR TITLE
Add Calendar

### PR DESCRIPTION
**Pull request by rick-gnous**
I'm trying to implement [CalendarMonth](https://www.patternfly.org/components/date-and-time/calendar-month). I must implement more things, like range, fix bugs and I would like to implement [DatePicker](https://www.patternfly.org/components/date-and-time/date-picker) with it. Actually, you can use it with a callback to get the new date and a default date.

I prefer to open this pull request early to get reviews and avoid mistakes. I'll try to continue the development next week if I've time.

I've also written a basic example for patternfly-yew-quickstart.

### CODE REVIEW

**Comment by ctron** [comment]
That's awesome. Just that you know, there's no need to "do it all". And if you think the API needs some more stabilization, we can always mark this as experimental like the `tree` (with a feature flag).

**Comment by rick-gnous** [comment]
I have a strange bug : when I change the month with buttons or by selecting a new date, the Select's `initial_selection` isn't updated. Else, I think it's good for this part, I'll start to add Date Selector.

**Comment by rick-gnous** [comment]
I've changed some `Callback::from` with `use_callback`. I'm working on `DatePicker` now.

Thank you for yours explanations ! If you can't take a look, I'll try to check it next week.

**Comment by ctron** [comment]
> If you can't take a look, I'll try to check it next week.

I don't want to promise anything. Whoever gets there first :wink:

**Comment by ctron** [comment]
@rick-gnous I just played with it. This is great!

I went ahead and created a new `SimpleSelect` component, based on the new, more modular, menu framework. I think this should be what you need. It's pushed to `main` and there is an example in the quickstart project.

Maybe I find some time this week to migrate your calendar to it.

**Comment by rick-gnous** [comment]
awesome, thank you ! I'll change my calendar for it. I'll also continue DatePicker !

**Comment by ctron** [comment]
Btw, it would be great if you could also push a (draft or not) PR for the quickstart … I had to "invent" one myself. Which also is fine. But if you already did the work, I wouldn't want to waste your effort.

**Comment by rick-gnous** [comment]
And I think we're good !

**Review by ctron — APPROVED** [review]

**Pull request merged**
