### PR TITLE
Implement dual list selector

### PR DESCRIPTION
**Pull request by aDogCalledSpot**
Implements the [dual list selector](https://www.patternfly.org/components/dual-list-selector/).

### Props

Currently supported properties:

- disabled
- pane titles
- options
- pane statuses
- onlistchange event

Currently unsupported properties but planned before merge:

- [x] additional classes
- [x] additional custom callbacks for control buttons
- [x] tooltip props
- [x] onoptionselect event

Currently unsupported properties which aren't planned for the merge:

- id
- tree
- onoptioncheck event
- aria
- searchable
- filtering
- dragging
- actions
- keyboard navigation

### Other stuff that needs to be done

- [x] I should document this as experimental and implement a feature gate
- [x] Insert a demo into the quickstart

## Implementation Details

Similar to how the table is currently implemented, I've defined a new trait `DualListSelectorItemRenderer` which has a blanket implementation for types implementing `Debug + Clone + PartialEq + ToHtml + 'static`. 
This type is used to render a single entry of a list in each of the two panes (available and chosen) by calling `to_html`.

## Open Questions

~~1. I see anymap is listed as a dependency for the project but it doesn't seem to be used anywhere, is this what I should be using for passing custom props to the tooltips?~~
~~2. Patternfly-react is serving the svg of the arrows in the control column but we are using the fa icon which leads to the icons not being centered properly. Would it be possible to serve the svg instead?~~
3. Are there any further acceptance criteria for this MR that I'm not aware of?

### CODE REVIEW

**Comment by ctron** [comment]
Awesome!

**Comment by aDogCalledSpot** [comment]
Additional tooltip props are working. I didn't realize they were just asking for the completely normal TooltipProperties.

**Comment by helio-frota** [comment]
oh this is a new impl , that's cool!

**Comment by aDogCalledSpot** [comment]
The off-center control buttons are due to the width not being fixed to "1em". [In patternfly-react all icons have a fixed width of 1em](https://github.com/patternfly/patternfly-react/blob/eb921ccf06a5b0ebe7ddcebd162f2e295260d8d4/packages/react-icons/src/createIcon.tsx#L49)

@ctron Should we update the icons in a separate PR to also behave like this or would you prefer I just force the 1em width in this instance alone?

**Comment by ctron** [comment]
That's an interesting issue. So far, the icons we are using are font based, not SVG based. I think it would make sense in general to provide some more support for alternatives. Because an "icon" should just be `Html`. Now that makes it more difficult I guess.]

Not sure there's a better solution to this at the moment. Maybe just ignore the issue for now and create an issue, tracking this and adding the information which you found. That would be very helpful I guess.

**Comment by aDogCalledSpot** [comment]
I tried forcing the width by using the `Icon::with_style` but that doesn't have any effect. Only setting the width on the `<i>` seems to work. So leaving it for now as you said.

**Comment by aDogCalledSpot** [comment]
Keyboard handling seems out of scope since we're missing the `handle_arrow_keys` function and it's out of scope for this PR.

I'll open a separate issue for it.

**Review by ctron — APPROVED** [review]

**Comment by aDogCalledSpot** [comment]
You can now have a look at the demos at https://github.com/aDogCalledSpot/patternfly-yew-quickstart/tree/dual_list_selector

**Review by ctron — APPROVED** [review]
Looks amazing! Let me know when you want to have it merged. We can always follow up on it!

**Pull request merged**
